image: "rust:latest"

stages:
    - test
    - build

test:fmt:
    stage: test
    script:
        - rustup component add rustfmt --toolchain 1.36.0-x86_64-unknown-linux-gnu
        - rustfmt --check src/*.rs

build:cargo:
    stage: build
    script:
        - rustc --version && cargo --version
        - cargo build