image: "rust:latest"

stages:
    - test
    - build
    - release
    - deploy

test:fmt:
    stage: test
    script:
        - rustup toolchain install nightly
        - rustup component add rustfmt --toolchain nightly
        - rustfmt +nightly --check src/*.rs
build:cargo:
    stage: build
    script:
        - rustc --version && cargo --version
        - cargo build

release:cargo:
    stage: release
    script:
        - cargo build --release
    artifacts:
        paths:
            - target/release/speculo
    only:
        - master

deploy_prod:
    stage: deploy
    environment:
        name: production
    script:
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
        - cargo build --release
        - scp target/release/speculo deploy@$DEPLOY_HOST:/usr/local/bin/speculo
    when: manual
