tab_spaces = 4
hard_tabs = true
reorder_imports = true
newline_style = "Unix"
brace_style = "PreferSameLine"
condense_wildcard_suffixes = true
empty_item_single_line = false
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
match_block_trailing_comma = true
merge_imports = true
reorder_impl_items = true
reorder_modules = true
spaces_around_ranges = false
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
unstable_features = true
normalize_comments = true
